app_index:
    path: /
    controller: App\Controller\PinController::index

app_show:
    path: /pins/{id<[0-9]+>}
    controller: App\Controller\PinController::show

app_create: 
    path: /pins/create
    controller: App\Controller\PinController::create
    methods: "GET|POST"
    
app_edit: 
    path: /pins/{id<[0-9]+>}/edit
    controller: App\Controller\PinController::edit
    methods: "GET|PUT|POST"

app_delete:
    path: /pins/{id<[0-9]+>}/delete
    controller: App\Controller\PinController::delete
    methods: "DELETE"
